using Microsoft.CodeAnalysis;
using System.Xml.Serialization;
using System.IO;
using System;
using SmartVault.Library;

namespace SmartVault.CodeGeneration
{
    [Generator]
    public class BusinessObjectSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            if (mainMethod is null)
            {
                return;
            }

            // Build up the source code
            for (int i = 0; i < context.AdditionalFiles.Length; i++)
            {
                var file = context.AdditionalFiles[i];
                var fileText = file.GetText(context.CancellationToken);
                if (fileText is null)
                {
                    continue;
                }

                var fileContents = fileText.ToString();

                var serializer = new XmlSerializer(typeof(BusinessObject));
                using var reader = new StringReader(fileContents);
                var name = Path.GetFileNameWithoutExtension(file.Path);
                if (serializer.Deserialize(reader) is not BusinessObject businessObjectModel ||
                    businessObjectModel.PropertyGroup?.Property is null)
                {
                    continue;
                }

                string propertiesString = "";
                var hasCreatedOn = false;
                for (int j = 0; j < businessObjectModel.PropertyGroup.Property.Count; j++)
                {
                    if (string.Equals(businessObjectModel.PropertyGroup.Property[j].Name, "CreatedOn", StringComparison.Ordinal))
                    {
                        hasCreatedOn = true;
                        break;
                    }
                }

                if (!hasCreatedOn)
                {
                    propertiesString += $"        public global::System.DateTime CreatedOn {{ get; set; }}{Environment.NewLine}";
                }

                for (int j = 0; j < businessObjectModel.PropertyGroup.Property.Count; j++)
                {
                    var property = businessObjectModel.PropertyGroup.Property[j];

                    propertiesString += string.Format(
                        "        public {0} {1} {{ get; set; }}{2}",
                        property.Type,
                        property.Name,
                        Environment.NewLine);
                }

                string businessObjectClassString = $@"// <auto-generated/>
namespace {mainMethod.ContainingNamespace.ToDisplayString()}.BusinessObjects
{{
    public partial class {name}
    {{
        {propertiesString}
    }}
}}
";
                context.AddSource($"{name}.generated.cs", businessObjectClassString);


            }
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}